/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beauty;
import Beauty.*;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class Inicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio2() {
        initComponents();
        this.setTitle("Inicio - Contabilidad");
        this.setLocationRelativeTo(null);
        transpareciaBoton();
        //setIconImage(new ImageIcon(getClass().getResource("imagenes1/LogoFamil.png")).getImage());
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFac = new javax.swing.JButton();
        jButtonPonchar = new javax.swing.JButton();
        jButtonFac2 = new javax.swing.JButton();
        jButtonFac1 = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFac.setBackground(new java.awt.Color(201, 116, 88));
        jButtonFac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/facturar bien.png"))); // NOI18N
        jButtonFac.setText("INVENTARIO");
        jButtonFac.setBorder(null);
        jButtonFac.setBorderPainted(false);
        jButtonFac.setContentAreaFilled(false);
        jButtonFac.setDefaultCapable(false);
        jButtonFac.setFocusPainted(false);
        jButtonFac.setFocusable(false);
        jButtonFac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 180, 250));

        jButtonPonchar.setBackground(new java.awt.Color(201, 116, 88));
        jButtonPonchar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonPonchar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPonchar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/clientes bien.png"))); // NOI18N
        jButtonPonchar.setText("PONCHAR");
        jButtonPonchar.setBorder(null);
        jButtonPonchar.setBorderPainted(false);
        jButtonPonchar.setContentAreaFilled(false);
        jButtonPonchar.setDefaultCapable(false);
        jButtonPonchar.setFocusPainted(false);
        jButtonPonchar.setFocusable(false);
        jButtonPonchar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPonchar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPonchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoncharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPonchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, 180, 250));

        jButtonFac2.setBackground(new java.awt.Color(201, 116, 88));
        jButtonFac2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFac2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/productos bien.png"))); // NOI18N
        jButtonFac2.setText("PRODUCTOS");
        jButtonFac2.setBorder(null);
        jButtonFac2.setBorderPainted(false);
        jButtonFac2.setContentAreaFilled(false);
        jButtonFac2.setDefaultCapable(false);
        jButtonFac2.setFocusPainted(false);
        jButtonFac2.setFocusable(false);
        jButtonFac2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFac2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 180, 240));

        jButtonFac1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFac1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFac1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/muslo.png"))); // NOI18N
        jButtonFac1.setText("FACTURAR");
        jButtonFac1.setBorder(null);
        jButtonFac1.setBorderPainted(false);
        jButtonFac1.setContentAreaFilled(false);
        jButtonFac1.setDefaultCapable(false);
        jButtonFac1.setFocusPainted(false);
        jButtonFac1.setFocusable(false);
        jButtonFac1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac1.setPreferredSize(new java.awt.Dimension(200, 182));
        jButtonFac1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFac1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 250));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/chicken.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void transpareciaBoton(){
        
    }
    private void jButtonFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacActionPerformed
        Inventario M = new Inventario();
        M.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonFacActionPerformed

    private void jButtonFac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFac1ActionPerformed
        Facturar F = new Facturar();
        F.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFac1ActionPerformed

    private void jButtonFac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFac2ActionPerformed
        Productos M = new Productos();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFac2ActionPerformed

    private void jButtonPoncharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoncharActionPerformed
        Ponchar R =new Ponchar();
        R.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPoncharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFac;
    private javax.swing.JButton jButtonFac1;
    private javax.swing.JButton jButtonFac2;
    private javax.swing.JButton jButtonPonchar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
