/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beauty;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Productos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ingreso cantidad - Contabilidad");
        
        //setIconImage(new ImageIcon(getClass().getResource("imagenes1/LogoFamil.png")).getImage());
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrar1 = new javax.swing.JButton();
        jButtonModificar2 = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonModificar1 = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrar1.setBackground(new java.awt.Color(201, 116, 88));
        jButtonRegistrar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonRegistrar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/pollo.png"))); // NOI18N
        jButtonRegistrar1.setText("INGRESAR CANTIDAD");
        jButtonRegistrar1.setAutoscrolls(true);
        jButtonRegistrar1.setBorderPainted(false);
        jButtonRegistrar1.setContentAreaFilled(false);
        jButtonRegistrar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonRegistrar1.setDefaultCapable(false);
        jButtonRegistrar1.setFocusPainted(false);
        jButtonRegistrar1.setFocusable(false);
        jButtonRegistrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar1.setRequestFocusEnabled(false);
        jButtonRegistrar1.setRolloverEnabled(false);
        jButtonRegistrar1.setVerifyInputWhenFocusTarget(false);
        jButtonRegistrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 250));

        jButtonModificar2.setBackground(new java.awt.Color(201, 116, 88));
        jButtonModificar2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonModificar2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/muslo.png"))); // NOI18N
        jButtonModificar2.setText("VENDIDO");
        jButtonModificar2.setBorderPainted(false);
        jButtonModificar2.setContentAreaFilled(false);
        jButtonModificar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 230, 250));

        jButtonRegistrar.setBackground(new java.awt.Color(201, 116, 88));
        jButtonRegistrar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/productos bien.png"))); // NOI18N
        jButtonRegistrar.setText("REGISTRAR  NUEVO ");
        jButtonRegistrar.setAutoscrolls(true);
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonRegistrar.setDefaultCapable(false);
        jButtonRegistrar.setFocusPainted(false);
        jButtonRegistrar.setFocusable(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.setRequestFocusEnabled(false);
        jButtonRegistrar.setRolloverEnabled(false);
        jButtonRegistrar.setVerifyInputWhenFocusTarget(false);
        jButtonRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 250));

        jButtonModificar1.setBackground(new java.awt.Color(201, 116, 88));
        jButtonModificar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonModificar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/confi.png"))); // NOI18N
        jButtonModificar1.setAutoscrolls(true);
        jButtonModificar1.setBorderPainted(false);
        jButtonModificar1.setContentAreaFilled(false);
        jButtonModificar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonModificar1.setDefaultCapable(false);
        jButtonModificar1.setFocusPainted(false);
        jButtonModificar1.setFocusable(false);
        jButtonModificar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar1.setRequestFocusEnabled(false);
        jButtonModificar1.setRolloverEnabled(false);
        jButtonModificar1.setVerifyInputWhenFocusTarget(false);
        jButtonModificar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 40, 70, 90));

        jButtonModificar.setBackground(new java.awt.Color(201, 116, 88));
        jButtonModificar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/dinero.png"))); // NOI18N
        jButtonModificar.setText("CAMBIAR PRECIO");
        jButtonModificar.setAutoscrolls(true);
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setContentAreaFilled(false);
        jButtonModificar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonModificar.setDefaultCapable(false);
        jButtonModificar.setFocusPainted(false);
        jButtonModificar.setFocusable(false);
        jButtonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar.setRequestFocusEnabled(false);
        jButtonModificar.setRolloverEnabled(false);
        jButtonModificar.setVerifyInputWhenFocusTarget(false);
        jButtonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 240, 250));

        jButtonAtras.setBackground(new java.awt.Color(201, 116, 88));
        jButtonAtras.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/atrasBlanco.png"))); // NOI18N
        jButtonAtras.setAutoscrolls(true);
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setContentAreaFilled(false);
        jButtonAtras.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonAtras.setDefaultCapable(false);
        jButtonAtras.setFocusPainted(false);
        jButtonAtras.setFocusable(false);
        jButtonAtras.setMinimumSize(null);
        jButtonAtras.setOpaque(true);
        jButtonAtras.setPreferredSize(null);
        jButtonAtras.setRequestFocusEnabled(false);
        jButtonAtras.setRolloverEnabled(false);
        jButtonAtras.setVerifyInputWhenFocusTarget(false);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 80, 40));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/chicken.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 1310, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        Registrar R = new Registrar();
        Productos I = new Productos();
        R.setVisible(true);
        I.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        ModificarPrecio M = new ModificarPrecio();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        Inicio2 I = new Inicio2();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar1ActionPerformed
        ModificarProducto mod = new ModificarProducto();
        mod.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonModificar1ActionPerformed

    private void jButtonModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar2ActionPerformed
        Vendido M = new Vendido();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonModificar2ActionPerformed

    private void jButtonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrar1ActionPerformed
        IngresoCantidadProductos I = new IngresoCantidadProductos();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRegistrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificar1;
    private javax.swing.JButton jButtonModificar2;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRegistrar1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
