/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Beauty;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author User
 */
public class RegistrarPollos extends javax.swing.JFrame {
    String user = "root";
    String clave = "";
    String url = "jdbc:mysql://localhost:3306/beauty";
    Connection con;
    Statement stmt;
    ResultSet rs;
    String datos[] = new String [4]; 
    DefaultTableModel modelo = new DefaultTableModel();
   
    
    /**
     * Creates new form Inicio
     */
    public RegistrarPollos() {
        
        initComponents();
        this.setTitle("Registrar pollos- Contabilidad");
        this.setLocationRelativeTo(null);
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RegistrarPollos.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        jTextFieldFecha.setText(fecha());
       
       buscarProducto("");
       AutoCompleteDecorator.decorate(jComboBoxCliente);
       jTextFieldCantidad.setText("1");
       cantidadPollos();
       
        

        
        
          
       
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jLabelPrecio5 = new javax.swing.JLabel();
        jScrollPaneProducto = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelPrecio3 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jButtonListo = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabelPrecio4 = new javax.swing.JLabel();
        jLabelPrecio2 = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelSumas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldFecha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextFieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaActionPerformed(evt);
            }
        });
        jTextFieldFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFechaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 240, -1));

        jTextFieldMonto.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoActionPerformed(evt);
            }
        });
        jTextFieldMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMontoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 240, -1));

        jLabelPrecio5.setBackground(new java.awt.Color(201, 116, 88));
        jLabelPrecio5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio5.setText("CANTIDAD:");
        jLabelPrecio5.setOpaque(true);
        getContentPane().add(jLabelPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 130, -1));

        TablaDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int riwIndex, int colIndex){
                return false;
            }
        };
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPaneProducto.setViewportView(TablaDatos);

        getContentPane().add(jScrollPaneProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 740, 60));

        jTextFieldCantidad.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 240, -1));

        jLabelPrecio3.setBackground(new java.awt.Color(201, 116, 88));
        jLabelPrecio3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio3.setText("PRODUCTO:");
        jLabelPrecio3.setOpaque(true);
        getContentPane().add(jLabelPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 150, -1));

        jComboBoxCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POLLO #13", "POLLO #14" }));
        jComboBoxCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxClienteMouseClicked(evt);
            }
        });
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 220, 40));

        jButtonListo.setBackground(new java.awt.Color(201, 116, 88));
        jButtonListo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonListo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListo.setText("REGISTRAR POLLOS");
        jButtonListo.setContentAreaFilled(false);
        jButtonListo.setOpaque(true);
        jButtonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, 40));

        jButtonCancelar1.setBackground(new java.awt.Color(201, 116, 88));
        jButtonCancelar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/x cancelar.png"))); // NOI18N
        jButtonCancelar1.setText("CANCELAR");
        jButtonCancelar1.setBorderPainted(false);
        jButtonCancelar1.setContentAreaFilled(false);
        jButtonCancelar1.setDefaultCapable(false);
        jButtonCancelar1.setOpaque(true);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 230, 50));

        jLabelPrecio4.setBackground(new java.awt.Color(201, 116, 88));
        jLabelPrecio4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio4.setText("FECHA:");
        jLabelPrecio4.setOpaque(true);
        getContentPane().add(jLabelPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 90, -1));

        jLabelPrecio2.setBackground(new java.awt.Color(201, 116, 88));
        jLabelPrecio2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio2.setText("VALOR:");
        jLabelPrecio2.setOpaque(true);
        getContentPane().add(jLabelPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 90, -1));

        jButtonInicio.setBackground(new java.awt.Color(201, 116, 88));
        jButtonInicio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/inicio.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.setOpaque(true);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, -1));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Pollo/chicken.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -70, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1310, 650));

        jLabelSumas.setText("jLabel1");
        getContentPane().add(jLabelSumas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void buscarProducto(String buscar){
        
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("TIPO");
        modelo.addColumn("PRECIO COMPRA");
        modelo.addColumn("CANTIDAD");
        
        modelo.addColumn("TOTAL");
        modelo.addColumn("FECHA");
        modelo.addColumn("MUSLO");
        modelo.addColumn("ALA");
        modelo.addColumn("CONTRA MUSLO");
        modelo.addColumn("PECHUGA");
         
        
        
        
        
        
        
        
        
        
        TablaDatos.setModel(modelo);

        
        
        String datos[] = new String [10];
         
        try {
            con = DriverManager.getConnection(url, user, clave);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM pollos WHERE id LIKE '%"+buscar+"%'");
            while(rs.next()){
                
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
                datos[3]= rs.getString(4);
                datos[4]= rs.getString(5);
                datos[5]= rs.getString(6);
                datos[6]= rs.getString(7);
                datos[7]= rs.getString(8);
                datos[8]= rs.getString(9);
                datos[9]= rs.getString(10);
                
                
                
                modelo.addRow(datos);
                
            }
            TablaDatos.setModel(modelo);
            TableColumn columna = TablaDatos.getColumn("ID");
            
            TableColumn columna2 = TablaDatos.getColumn("CANTIDAD");
            
            
            TableColumn columna7 = TablaDatos.getColumn("PRECIO COMPRA");
            
            
            columna.setMinWidth(48);
            columna.setMaxWidth(48);
            
            columna2.setMinWidth(70);
            columna2.setMaxWidth(70);
            
            
            columna7.setMinWidth(95);
            columna7.setMaxWidth(95);
            
        } catch (SQLException ex) {
            Logger.getLogger(Vendido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    void seleccionarCliente(String sele){

        try {
             
            con = DriverManager.getConnection(url, user, clave);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM pollos WHERE tipo LIKE '%"+sele+"%' ORDER BY tipo ASC");

                while(rs.next()){
                    jTextFieldMonto.setText(rs.getString(3));                   
                }
                         
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPollos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void cantidadPollos(){
        double menor=Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, 6).toString()) / 2);
        for(int i=7;i<9;i++){
            if(Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, i).toString())/2)<menor){
            menor=Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, i).toString())/2);
            }
        }
        if(Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, 9).toString())/4)<menor){
            menor=Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, 9).toString())/4);
        }
        boolean sw=false;
        for(int i=6;i<9;i++){
            double valor=Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, i).toString())/2);
            if(valor>=(menor+1) && sw==false){
            menor+=1;
            sw=true;
            }
        }
        if(Math.ceil(Double.parseDouble(TablaDatos.getValueAt(1, 9).toString())/4)>=(menor+1) && sw==false){
            menor+=1;
            sw=true;
        }
        
        TablaDatos.setValueAt(menor, 1, 3);
        
        try {
                  con = DriverManager.getConnection(url, user, clave);
                  stmt = con.createStatement();

                  stmt.executeUpdate("UPDATE pollos SET cantidad = '"+menor+"' WHERE id = '2'");
                 
                } catch (SQLException ex) {
                  Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }
    
    
     public static String fecha(){
       Date fecha = new Date();
       SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
       return formatofecha.format(fecha);
    }
     
    
    
    
    private void jTextFieldMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoKeyTyped
        char n = evt.getKeyChar();
        if(n < '0' || n> '9') evt.consume();
    }//GEN-LAST:event_jTextFieldMontoKeyTyped

    private void jTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoActionPerformed

    private void jButtonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListoActionPerformed
        boolean sw2=false;
        
            
        if(jTextFieldMonto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No ingresó el precio de compra");
            sw2=true;
        }else if(jTextFieldFecha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No ingresó la fecha");
            sw2=true;
        }else if(jTextFieldCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No ingresó la cantidad");
            sw2=true;
        }else if(sw2==false){
           
           double precioCompra=0 , ganancia=0 , total=0 , pos=0, total2=0;
           double cantidad=0;
           int fila = TablaDatos.getRowCount();
           boolean sw =true;

                
                total = Double.parseDouble(jTextFieldCantidad.getText()) * Double.parseDouble(jTextFieldMonto.getText());
                
                
              if(jComboBoxCliente.getSelectedItem().toString().equals("POLLO #13")){
                  total2 = total + Double.parseDouble(TablaDatos.getValueAt(0, 4).toString());
                  cantidad = Double.parseDouble(jTextFieldCantidad.getText()) + Double.parseDouble(TablaDatos.getValueAt(0, 3).toString());
                try {
                  con = DriverManager.getConnection(url, user, clave);
                  stmt = con.createStatement();

                  stmt.executeUpdate("UPDATE pollos SET cantidad = '"+cantidad+"' WHERE id = '1'");
                  stmt.executeUpdate("UPDATE pollos SET total = '"+total2+"' WHERE id = '1'");
                  stmt.executeUpdate("UPDATE pollos SET precioCompra = '"+jTextFieldMonto.getText()+"' WHERE id = '1'");
                  stmt.executeUpdate("UPDATE pollos SET fecha = '"+jTextFieldFecha.getText()+"' WHERE id = '1'");
                  

                } catch (SQLException ex) {
                  Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                  cantidad = Double.parseDouble(jTextFieldCantidad.getText()) + Double.parseDouble(TablaDatos.getValueAt(1, 3).toString());
                  String vector[] = {"muslo", "ala", "contramuslo", "pechuga"};
                  total2 = total + Double.parseDouble(TablaDatos.getValueAt(1, 4).toString());
                  int j=6;
                  double presas=0;
                  double pollos=0;
                try {
                  con = DriverManager.getConnection(url, user, clave);
                  stmt = con.createStatement();

                  stmt.executeUpdate("UPDATE pollos SET cantidad = '"+cantidad+"' WHERE id = '2'");
                  stmt.executeUpdate("UPDATE pollos SET total = '"+total2+"' WHERE id = '2'");
                  stmt.executeUpdate("UPDATE pollos SET precioCompra = '"+jTextFieldMonto.getText()+"' WHERE id = '2'");
                  stmt.executeUpdate("UPDATE pollos SET fecha = '"+jTextFieldFecha.getText()+"' WHERE id = '2'");
                  for(int i=0; i<4; i++){
                      if(vector[i]!="pechuga"){
                        presas = Double.parseDouble((String) TablaDatos.getValueAt(1, j)) + 2*Double.parseDouble(jTextFieldCantidad.getText());
                      }else{
                        presas = Double.parseDouble((String) TablaDatos.getValueAt(1, j)) + 4*Double.parseDouble(jTextFieldCantidad.getText()); 
                      }
                      stmt.executeUpdate("UPDATE pollos SET "+vector[i]+" = '"+presas+"' WHERE id = '2'");
                      j++;
                      presas =0;
                  }

                } catch (SQLException ex) {
                  Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
            
           JOptionPane.showMessageDialog(null, "Registro exitoso");
            
            
           modelo.setRowCount(0);
           buscarProducto("");
           jTextFieldCantidad.setText("1");
        }
    }//GEN-LAST:event_jButtonListoActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        
        jTextFieldMonto.setText("");
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        Inicio2 I = new Inicio2();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jTextFieldFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaKeyTyped

    private void jComboBoxClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxClienteMouseClicked

    }//GEN-LAST:event_jComboBoxClienteMouseClicked

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        String selectedValue = jComboBoxCliente.getSelectedItem().toString();
        
        seleccionarCliente(selectedValue);
        
        
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jTextFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPollos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPollos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPollos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPollos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPollos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaDatos;
    public javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonListo;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPrecio2;
    private javax.swing.JLabel jLabelPrecio3;
    private javax.swing.JLabel jLabelPrecio4;
    private javax.swing.JLabel jLabelPrecio5;
    private javax.swing.JLabel jLabelSumas;
    private javax.swing.JScrollPane jScrollPaneProducto;
    public javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldFecha;
    public javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
